from __future__ import annotations

import argparse
import json
from pathlib import Path

from app.replay import load_and_summarize


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Summarize HFT runner telemetry JSONL output.")
    parser.add_argument(
        "--telemetry-path",
        default=str(Path("runtime") / "hft-runner.jsonl"),
        help="Path to the JSONL telemetry file generated by app.runner_cli.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    summary = load_and_summarize(args.telemetry_path)
    print(json.dumps(summary, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
